### PR TITLE
Enhancement: group nesting/subgroups

### PR DESCRIPTION
**Pull request by DamitusThyYeetus123**
## Proposed change

Adds Nested groups and subgroups, with the following formatting

```yaml
- Group A:
  - Subgroup A:
      type: group
      services:
        - Service A:
            href: http://localhost/
  - Service B:
      href: http://localhost/

- Group B:
    - Service C:
        href: http://localhost/
```

Closes #2310 

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Not to be a downer here, but can I ask what this actually accomplishes? This basically allows the user to have 1-level deeper nesting of services, ie. it adds a second level title that looks exactly the same and groups those inside a box?

At least as is, you cannot set a different icon, use a different layout style (rows vs columns) and overall I do not find it aesthetically pleasing at all:

Screenshot 2024-11-27 at 12 15 56 AM
Screenshot 2024-11-27 at 12 16 13 AM

I hate to say it but I would not merge this as-is...

**Comment by shamoon** [comment]
Also, doesnt work with docker labels

**Comment by DamitusThyYeetus123** [comment]
I’ll add all those changes you’ve mentioned, and i will say that I added it due to the fact that it’s the most requested non-widget feature in discussions.

**Comment by shamoon** [comment]
Again, most requested does not always necessarily mean belongs in this project. Sometimes features get up-voted because they've hung around for a while. I see my role as a maintainer as a steward of the project as much as anything else, i.e. to maintain its quality and keep it focused.

I worry this is going to get messy...

**Comment by DamitusThyYeetus123** [comment]
I think this feature is something basic enough that it makes sense in the project. If this idea isn't wanted in the project, that's fine, but I do think that something like this would benefit the project.

**Comment by DamitusThyYeetus123** [comment]
In terms of stylistic changes, i'm implementing `style: row` and `icon: ...` for subgroups.

**Comment by DamitusThyYeetus123** [comment]
image
Icons done, just row/column stuff left

**Comment by DamitusThyYeetus123** [comment]
image
Here is mixing columns and rows

**Comment by DamitusThyYeetus123** [comment]
image
Using subgroups and `header: false` to mix columns and rows more seamlessly

**Comment by shamoon** [comment]
Sorry Im not happy with this PR, I'm going to close it for now and have a think about how to do this, but stuff like this is generally very poor practice:

```
      .filter((entry) => entry[Object.keys(entry)[0]].type == "group")
       .map((entries) => ({
         style: entries[Object.keys(entries)[0]].style,
         icon: entries[Object.keys(entries)[0]].icon,
         columns: entries[Object.keys(entries)[0]].columns,
         header: entries[Object.keys(entries)[0]].header,
         ...mappingFunc(entries, entries[Object.keys(entries)
```

You are iterating an object, creating arrays repeatedly etc.

In general I'd really prefer you try to tackle some smaller PRs, the review requirement here is very high for these things that touch a lot of different parts of the app.

Thanks

**Pull request closed without merging**
