### PR TITLE
Fix: react-icons must be ^5.0.0 to resolve ES conflicts

### PR DESCRIPTION
**Pull request by ConnerWithAnE**
## Proposed change

I tried to run the dev server and ran into errors pertaining to react-icons. Prior to v5 imports must be done as `react-icons/fi/index.js` and the required version was ^4.12.0 which is too low. Changed the minimum to 5.2.1 (current version)

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
I’ll look later but this doesn’t really make sense to me. If the current package lock didn’t resolve the docker container etc wouldn’t build. Did you install with `pnpm install`?

**Comment by ConnerWithAnE** [comment]
Yea I ran `pnpm` install several times, tried just `npm install` too. With `pnpm` I always ran into this error, I don't know why it didn't resolve it. It does not make sense to me either. After googling the error a bit I found someone saying that this was a known error that was resolved in `react-icons` v5 maybe it has something to do with the chore updates?

**Comment by shamoon** [comment]
Yea I think this is a local thing, this also isnt a correct diff to upgrade. Try removing the pnpm cache, reinstalling etc, I don't think the current lock files are broken tho.

**Comment by ConnerWithAnE** [comment]
How would I remove the pnpm cache? I deleted the entire repo and recloned, ran pnpm install and had the same issue.

**Comment by shamoon** [comment]
Im not certain what is up for you, https://pnpm.io/cli/store#prune ?

But again, this is what ci does too https://github.com/gethomepage/homepage/actions/runs/9025376244/job/24801006393

**Pull request closed without merging**
