### PR TITLE
Enhancement: allow api auth with moonraker service

### PR DESCRIPTION
**Pull request by stevendejongnl**
## Proposed change

Changed the genericProxyHandler to use the credentialedProxyHandler for moonraker instances that uses authorization by API keys.
With the genericProxyHandler you get a 401 unauthorized error on those instances.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by shamoon** [comment]
Please provide an explanation and or / link to a discussion, even if the change seems obvious. It doesn’t seem any other moonraker users have asked about auth

**Comment by stevendejongnl** [comment]
> Please provide an explanation and or / link to a discussion, even if the change seems obvious. It doesn’t seem any other moonraker users have asked about auth

Sorry, I submitted to quickly.
Updated the description

**Comment by shamoon** [comment]
Thanks. So moonraker api uses 

https://github.com/gethomepage/homepage/blob/36585a2c44acda10bea1c7a1efe0ef78956b213d/src/utils/proxy/handlers/credentialed.js#L69

?

**Comment by stevendejongnl** [comment]
> Thanks. So moonraker api uses
> 
> https://github.com/gethomepage/homepage/blob/36585a2c44acda10bea1c7a1efe0ef78956b213d/src/utils/proxy/handlers/credentialed.js#L69
> 
> ?

Thats correct:
https://moonraker.readthedocs.io/en/latest/web_api/#authorization

**Comment by stevendejongnl** [comment]
> Also, thing to check here is that it won’t break non-auth instances…
> 
> (also assuming it never allows basic auth, which this would also break)



> Also, thing to check here is that it won’t break non-auth instances…
> 
> (also assuming it never allows basic auth, which this would also break)

Good point, I will spin up another instance without authentication to check this.

**Comment by shamoon** [comment]
Great thanks. Yea as you can guess I don’t have an instance to test.

Thanks for the docs link, yea in this case please update the homepage docs to note the optional `key` parameter

**Comment by stevendejongnl** [comment]
> Great thanks. Yea as you can guess I don’t have an instance to test.
> 
> Thanks for the docs link, yea in this case please update the homepage docs to note the optional `key` parameter

I can confirm that an instance without authentication and no key set in the configuration does work:
image
image

**Review by shamoon — APPROVED** [review]
Thanks for confirming that.

I don't really think this is a bug but since it literally adds 0 code thats cool. Do try to mind the PR requirements (checkboxes you removed) in the future (here and in general).

**Pull request merged**
