### PR TITLE
Documentation: clarify api key usage for pfsense v1 vs v2

### PR DESCRIPTION
**Pull request by nopoz**
Fixing pfSense widget documentation for usage with an API key. Current documentation has incorrect header of `Authorization` and a value of `client_id client_token`. The correct header name is `X-API-Key` and the value is the API `key` produced by the pfSense v2 API package. I have tested this format and it works as expected. 

Example working config for reference:

```
    - pfSense:
        icon: pfsense.png
        href: https://pfsense.example.com
        description: router
        widget:
            type: pfsense
            url: https://pfsense.example.com
            headers:
              X-API-Key: 12345678
            wan: ix0
            version: 2
            fields: ["load", "memory", "wanStatus", "wanIP"]
```
pfSense API authorization documentation is here: https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/

## Proposed change

Closes [Discussion #3716](https://github.com/gethomepage/homepage/discussions/3757)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
I don’t have a pfsense but it seems odd to me that the current highly-specific documentation would be made-up, so the only way would be if something changed. Perhaps in the recent pfsense v2? If so, this change would be confusing

**Comment by nopoz** [comment]
> I don’t have a pfsense but it seems odd to me that the current highly-specific documentation would be made-up, so the only way would be if something changed. Perhaps in the recent pfsense v2? If so, this change would be confusing

Looks like "Authorization: client_id client_token" is only for the v1 API version documented here: https://github.com/jaredhendrickson13/pfsense-api/tree/legacy?tab=readme-ov-file#authentication--authorization

The version I've added is for v2 only.

**Comment by nopoz** [comment]
I suppose there could be two different code blocks in the readme for v1 and another for v2?

**Comment by shamoon** [comment]
> I suppose there could be two different code blocks in the readme for v1 and another for v2?

Yes, my point is it should be made clearer

**Review by shamoon — APPROVED** [review]

**Pull request merged**
