### PR TITLE
Added instructions on how to restrict Omada User privileges for widget

### PR DESCRIPTION
**Pull request by Jannik-Hm**
## Proposed change

Added instructions on how to restrict Omada User privileges for Omada widget

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation only
- [ ] Other (please explain)

## Checklist:

- [ ] If applicable, I have added corresponding documentation changes.
- [ ] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
We dont like to include instructions for other software here. If there's a link to the Omada docs about this we'd accept that.

**Comment by Jannik-Hm** [comment]
It only came to my mind, since the Proxmox and Opnsense widget contained similar instructions

**Comment by shamoon** [comment]
And they are constantly getting PR’d with “I did this instead”. It’s frustrating because these kind of instructions sometimes depend on version, UIs can change etc so it seems like we’re just asking for more documentation maintenance burden. That’s why I’d ask for a link to some official documentation, let the actual makers of the product maintain the details.

I suppose if you’d like to make this more generic like opnsense “only the following privileges are required” that could work

Thanks for your understanding

**Comment by Jannik-Hm** [comment]
I see, thank you very much for the further explanation.

**Pull request closed without merging**
