### PR TITLE
Documentation: add optional auth to whatsupdocker documentation

### PR DESCRIPTION
**Pull request by zmweske**
Tested and user/pass do indeed work

## Proposed change

Found that the widget does indeed support when the remote server uses authentication. Tested on desktop and mobile with both http & https. 

Closes # (issue)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [ ] ~~If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).~~
- [ ] ~~I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).~~
- [x] ~~If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.~~

### CODE REVIEW

**Comment by shamoon** [comment]
https://github.com/gethomepage/homepage/commit/fa1d343f2a1a9f809c9c8f1cdeb01ea47498d9ad

**Comment by zmweske** [comment]
Why was this closed and moved to a different commit?

**Comment by shamoon** [comment]
Your original PR was not correctly made so I fixed it and accidentally did that in the main branch instead. You are still attributed to that commit.

Nest time it would help to correctly format the PR from the start, thanks

**Comment by zmweske** [comment]
sure #3113 had two extra whitespace characters but I fixed that and made a new request. I checked out https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks and https://github.com/gethomepage/homepage/blob/main/CONTRIBUTING.md and the only thing I can think of is the pre-commit hooks, which didn't run as I made the documentation change directly on github. What else can I do better next time?

**Comment by shamoon** [comment]
Yea that’s all I mean, running the pre-commit hooks to correctly format it and the tests pass, you know just trying to make a PR (especially when something small) as “frictionless” as possible for the maintainers. It’s not a “big deal” but something to keep in mind if you want to do more contributing

**Comment by zmweske** [comment]
Sounds good, thanks and thanks for your work

**Pull request closed without merging**
