### PR TITLE
Enhancement: extend TrueNAS widget and add info widget

### PR DESCRIPTION
**Pull request by dstotz**
## Proposed change

- Maintain the previous behavior with previous configuration
- Add new optional parameter for `enablePools` that when enabled will display each Pool in the TrueNAS instance with its disk usage, and a status indicator
- Add new information widget for TrueNAS that when configured will show the system resources for your TrueNAS instance mirroring the display of the Kubernetes information widget
- Refactor existing Kubernetes information widget into a reusable component for future use (no change to Kubernetes functionality or UI/UX)

Below is an example of the new `enablePools` option for the existing service widget

image

Below is an example of the new `truenas` information widget

image

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [X] Other (please explain) - New information widget

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks, a couple things:

1. in general, please don’t group unrelated changes into one PR (though perhaps they are dependent on each other here?)
2. Please review the guidelines. Changes like this need to target existing up-voted FRs

We’d be happy to revisit this PR(s) at a later date.

**Comment by dstotz** [comment]
@shamoon understandable, and my apologies. I thought the upvote requirement was only to add a new service widget, not to enhance an existing one, but upon re-reading... I am an idiot haha.

I will start by creating the feature requests and if they get enough upvotes I will happily rebase my changes at that time.

**Comment by dstotz** [comment]
Feature requests for reference

Pool enhancement: https://github.com/gethomepage/homepage/discussions/2792
information widget: https://github.com/gethomepage/homepage/discussions/2791

**Comment by shamoon** [comment]
No worries thanks for your understanding

**Pull request closed without merging**
