### PR TITLE
Favicons

### PR DESCRIPTION
**Pull request by jonnymccullagh**
## Proposed change
The bookmarks component uses a lot of horizontal space and I was looking for a mechanism to add a row of icons each linking to a corresponding URL. I have copied much of the existing bookmarks code to create a favicons component controlled by additions to a `favicons.yaml` config file. The example screenshot below shows some favicons under the traditional bookmarks:
favicons

Discussion [here](https://github.com/gethomepage/homepage/discussions/4294)

Please feel free to suggest changes.

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [ ] If applicable, I have reviewed the [feature](https://gethomepage.dev/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines).
- [ ] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/more/development/#code-linting).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by markalex2209** [comment]
@shamoon, if I understand correctly, threshold for FR is met now.

**Comment by jonnymccullagh** [comment]
> @shamoon, if I understand correctly, threshold for FR is met now.

@markalex2209 is the threshold met because of votes on the discussion [here](https://github.com/gethomepage/homepage/discussions/4294) ? I am new to this project.

**Comment by markalex2209** [comment]
I'm also new to this project, but [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines) mention:
> Please only submit widgets that target a feature request discussion with at least 10 'up-votes'. The purpose of this requirement is to avoid the addition (and maintenance) of service widgets that might only benefit a small number of users.

And I noticed, that your discussion already has +10, so brought this up.

**Comment by shamoon** [comment]
1. We removed the exact number requirement for non-widget FRs. So while Im not really sure that 10 votes is indicative of a widespread interest for this, we take these on a case-by-case basis.
2. More importantly, the issue with this PR (now that I look at it) is that I am not happy with this approach to the implementation. This PR is nearly 100% duplicated code from elsewhere and requires an entire new config. I'm sorry if this comes across as obnoxious but rather than request this PR be re-done I went ahead and implemented how I think it should be done in #4384

**Comment by jonnymccullagh** [comment]
thank you @markalex2209 for your input and thank you @shamoon for implementing the change. The fork, PR were for my own use but now looking forward to seeing this implemented for everyone. Cheers.

**Pull request closed without merging**
