### PR TITLE
Add LOG_TARGETS environment variable to control log outputs

### PR DESCRIPTION
**Pull request by jnsgruk**
Adds a config option to enable customisation of where homepage logs to. This is controlled through an environment variable `LOG_TARGETS` to complement the existing `LOG_LEVEL` variable. Options include `both` (default), `stdout` and `file`.

The default is "both" to preserve backwards compatibility.

This is useful in cases where logs are already collected from `stdout` by a central service, and thus the log file is redundant or otherwise requires logrotate.

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks. We only accept feature PRs that target an (up-voted) request, see the guidelines checkbox above. Is there one for this?

**Comment by jnsgruk** [comment]
Oops, no - should I create one?

My motivation for this is as the maintainer of the NixOS module for homepage, which is getting an overhaul to make the homepage config supported in the next release of the OS.

**Comment by shamoon** [comment]
> Oops, no - should I create one?

That is the standard we ask of everyone, so I'm not sure its fair to do otherwise 🫤

Typically we dont keep these PRs open in the meantime...

NixOS is interesting, people seem to swear by it but frankly it seems to frequently require bespoke handling (lots of similar experiences in some of my other FOSS projects).

**Comment by jnsgruk** [comment]
No probs, I'll close this for now and create an issue. Thanks!

**Comment by shamoon** [comment]
And I guess #1673 is no longer sufficient?

**Pull request closed without merging**
