### PR TITLE
Enhancement: support Tdarr widget auth

### PR DESCRIPTION
**Pull request by Wtfitsaduck**
## Proposed change

Add Tdarr widget optional auth
Addresses already closed issue #2704, relevant to discussion #2705.
I realize the discussion does not have 10 upvotes as required, but I think this is a simple enough addition🙂

Also was unsure which branch to merge to so I hope main is alright 🤞  

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
I agree it’s a simple PR but it still needs to be tested, maintained etc. And maybe it seems silly, but I think it’s only fair that we hold all contributions to the same standards. That’s why we have them after all.

I’ll close this for now but we can readdress if / when needed. I’ve updated that discussion to be more of a feature request.

Thanks for your interest.

**Comment by perfectra1n** [comment]
@shamoon this would be equivalent to #3846 where functionality was added to support authentication to an already existing widget. Tdarr is an approved widget (#404 and #687) but now supports authentication, and these changes would fix the now broken widget for its users.

**Comment by shamoon** [comment]
Its got 10 votes now anyway

**Review by shamoon — APPROVED** [review]
Please see my code changes

Screenshot 2024-09-04 at 3 58 43 PM

**Pull request merged**
