### PR TITLE
Feature: Romm Widget

### PR DESCRIPTION
**Pull request by karl0ss**
## Proposed change

Add Romm service widget

Closes #2550

## Type of change

- [X] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
@karl0ss are you able to address the lint errors (you checked the box but didnt do that I think), documentation and merge conflict?

**Comment by karl0ss** [comment]
I will, but am busy this week, I couldn't get the docs to install, haven't retired since your last push, but yeah I can fix the issues and will open the pr as non draft, I'll see if I get some time tomorrow to do it.

**Review by shamoon — APPROVED** [review]
Screenshot 2024-01-19 at 11 32 24 PM

**Comment by karl0ss** [comment]
Thanks for your help on this, I am having a nightmare trying to get pre-commit running....just to mention, this will need slight updating as if you are using auth in romm you need this in your services.yaml

```
 - Rom Manager:
    icon: romm
    href: <URL>
    widget:
      type: romm
      url: <URL>
      username: <Username>
      password: <Password>
```

**Comment by shamoon** [comment]
Ah. What type of auth does the romm api use? I didnt look for too long but I didnt see docs

**Comment by gantoine** [comment]
@shamoon  Requests can be made to protected API endpoints with an authorization header. The token is the base64 encoded value of `username:password`. Example using cURL: `curl https://romm.local/api/platforms -H 'Authorization: Basic YWRtaW46aHVudGVyMg=='`

**Comment by shamoon** [comment]
Great thanks. That should work "out of the box" already

**Comment by karl0ss** [comment]
Yeah they work out the box via the standard proxy

**Pull request merged**
