### PR TITLE
feat: adding a widget n8n

### PR DESCRIPTION
**Pull request by julienfroidefond**
## Proposed change

Adding a service widget for n8n service. Code is really simple (wel done on your mappers :) ). 
I have just some questions on going; about the totals. Executions is maybe a little too large.
Workflows = length of the API workflows with `workflows?active=true`
Executions = length of the API executions with `executions?includeData=false&status=success`
image

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added corresponding documentation changes.
- [x] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using pre-commit hooks and linting checks with `pnpm lint` (see development guidelines).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by benphelps** [comment]
Do not change all locales, only add English and languages you can natively translate, [Crowdin](https://crowdin.com/project/gethomepage) will handle other locales.

**Comment by benphelps** [comment]
Our general rule is that an integration have at least 5 votes before it gets merged in, following that, this may need to wait a bit.

**Comment by shamoon** [comment]
Yes, please read the guidelines you checked off above. Actually only edit the English locale at all. Everything else should come crowdin. We’ll reopen when the time comes, feel free to ping us.

Thanks for the PR

**Comment by julienfroidefond** [comment]
Hello, thanks for your comments. I saw the five votes but not the locales guideline. 
I have try at least ! :)
Another time, so

**Comment by julienfroidefond** [comment]
Cf https://github.com/gethomepage/homepage/discussions/2379

**Pull request closed without merging**
