### PR TITLE
Fix: Peanut widget v2 api compatibility

### PR DESCRIPTION
**Pull request by Brandawg93**
## Fix for peanut v2 api

Closes # (issue)

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [ ] If applicable, I have added corresponding documentation changes.
- [ ] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Thanks

**Comment by xxirs** [comment]
@Brandawg93 @shamoon Pretty sure there's still a bug within the latest homepage (0.8.5) and PeaNUT 2.3.0

PeaNUT 2.2.1 works with homepage, 2.3.0 does not.

image

**Comment by Brandawg93** [comment]
Should be fixed in v2.3.1 of peanut.

**Comment by shamoon** [comment]
Awesome thanks Brandawg93

**Comment by Brandawg93** [comment]
This is confirmed fixed now! @shamoon feel free to close this whenever.

**Pull request merged**
