### PR TITLE
Fix: wg-easy widget show o.filter is not a function when wg-easy api return error

### PR DESCRIPTION
**Pull request by BugGeeker**
## Proposed change

image

Closes #3658 

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
What does wg-easy actually return in this case?

**Comment by BugGeeker** [comment]
> What does wg-easy actually return in this case?

image

**Comment by shamoon** [comment]
Right, so instead of checking for an array, please change it to check the statusCode

Perhaps more importantly, why is your wg-easy throwing an error 500?

**Comment by BugGeeker** [comment]
> Right, so instead of checking for an array, please change it to check the statusCode
> 
> Perhaps more importantly, why is your wg-easy throwing an error 500?

I make a commit to change the check method.

I don't know why wg-easy throwing 500, It's normal on wg-easy webui.

**Comment by shamoon** [comment]
Thanks. And please revert the unrelated change

**Comment by BugGeeker** [comment]
done.

**Review by shamoon — APPROVED** [review]
Thanks

**Pull request merged**
