### PR TITLE
Change: use Script component instead of async script for custom.js

### PR DESCRIPTION
**Pull request by Cyberbeni**
## Proposed change

Closes #2900 

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [ ] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Hmm, not sure this will work because the site is compiled statically, that has always been the challenge with custom js. Lets see.

**Comment by shamoon** [comment]
Well great, does seem to work for me, thats great. Did you test the docker image as well?

I suppose theres the chance this affects existing users in unexpected ways, at worst seems like the script will run later than previously.

**Comment by Cyberbeni** [comment]
Yes, I tested it by building the docker image locally.

**Review by shamoon — APPROVED** [review]
Great, yea me too. This will sit in `main` for a while until our next release, we'll see if anything comes up. Not sure how we didnt try this before...

Thanks for the PR

**Pull request merged**
