### PR TITLE
Feature: ESPHome widget

### PR DESCRIPTION
**Pull request by RoboMagus**
## Proposed change

image

This adds a service widget for ESPHome, as the CustomAPI widget does not allow for API response data processing as required to get the sum of devices per state.

Closes #2070

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Please reopen when ready

**Comment by RoboMagus** [comment]
> Please reopen when ready

That's why I had it as draft and not yet as ready...

**Comment by RoboMagus** [comment]
@shamoon, please reopen. Discussion #2070 passed the 10 vote threshold.

**Review by shamoon — APPROVED** [review]
Screenshot 2024-03-03 at 8 57 40 AM

**Pull request merged**
