### PR TITLE
Documentation: fix indentation for proxmox docs.

### PR DESCRIPTION
**Pull request by Trevo525**
## Proposed change
I added one space for the indentation of the proxmox.md. It's how it's supposed to be but since they only have three spaces they aren't indented properly.

image

The screenshot shows that the first two things would look like the third set of things.

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by Trevo525** [comment]
I'd be happy to if I knew what you meant. I matched the formatting to the ones that did it correctly and they didn't have a blank line before them..

**Comment by shamoon** [comment]
Yea, as I said I dont exactly remember. The others pass the pre-commit hooks, so you can install pre-commit as is recommended and experiment a bit to fix it. Or not.

**Comment by Trevo525** [comment]
Ah, I didn't understand per-commit as a project. I understood it as you saying before my commit. That's why I didn't understand what you meant. I'll probably look into this later.

**Review by shamoon — APPROVED** [review]
Screenshot 2024-08-23 at 8 04 05 PM

**Pull request merged**
