### PR TITLE
Fix: Improve error handling for Glances widgets

### PR DESCRIPTION
**Pull request by mjsully**
## Proposed change

I have the Glances widgets deployed in my Homepage instance and noticed that when a host is unreachable the widgets do not handle the errors as the other widgets do. It results in an ugly error message which doesn't respect either the global or service-level `hideErrors`. Here is an example from my deployment:

glances-widget-bug

I have rewritten parts of the components such that the `Error` component is no longer needed, as it is now implemented within the `Container` component. The service and error attributes are now passed into the `Container` component, such that the service-level `hideErrors` flag can be checked. Additionally, the global settings are now imported into the `Container` component so the global `hideErrors` flag can be checked. Within each component, if the service data containers an "error" key,  the widget will now display an error message in line with other widgets. See the screenshot below:

glances-widget-fix-showErrors

Additionally, see the below screenshot testing the service-level `hideErrors` flag set to `true` for one widget:

glances-widget-fix-hideErrors

## Type of change

- [ ] New service widget
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [ ] If applicable, I have added corresponding documentation changes.
- [ ] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
I can take a real look at this soon but my first thought is that the logic to respect errors should just be moved inside Error, instead of all the other changes for removing it. and in info and gpu where you check for the error property presumably that should become the error for the Error component

**Comment by shamoon** [comment]
Sure, but separating them logically makes sense and that's also how the rest of the app does it. Also would significantly reduce the diff here.

Let us know if youre OK making the change, I can also take care of it if thats better.

**Comment by mjsully** [comment]
Sure, let me make the changes and commit.

**Comment by mjsully** [comment]
I've now reintroduced the error component and import it within the container component. Following the implementation style in e.g. the Home Assistant widget https://github.com/gethomepage/homepage/blob/ec448d6c41ffa7c90c4a180a972eff309ebbcf3d/src/widgets/homeassistant/component.jsx#L10 the error handling is still done within the container component. Let me know if you want any other changes making.

**Comment by shamoon** [comment]
That wasnt exactly what I had in mind. Please take a look at the changes here. (also FYI https://eslint.org/docs/latest/rules/no-prototype-builtins )

**Comment by shamoon** [comment]
Edit: and let me know if you have any thoughts or concerns

**Comment by mjsully** [comment]
Thanks for this, and thanks for the link that's good to know. As for the changes, it seems like there isn't a consistent implementation of the error handling (e.g. the Home Assistant ref I provided was similar to my own implementation but different to the one you have provided in the changes.) - either way the result will be the same and looks good to me.

**Comment by shamoon** [comment]
Point taken, I've gone back to a bit of a mix

**Review by shamoon — APPROVED** [review]
Ok, thanks again

**Pull request merged**
