### PR TITLE
Feature: Added agenda view for calendar, calendar improvements

### PR DESCRIPTION
**Pull request by denispapec**
## Proposed change

This PR adds agenda view for calendar, contains additional improvements to show when event has completed status (for example media has available file),  and add additional configuration to limit number of events in the event list.

Closes #2106
Closes #2097

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added corresponding documentation changes.
- [x] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using pre-commit hooks and linting checks with `pnpm lint` (see development guidelines).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks as always, I did run into a bunch of issues. The commits should explain most of them.

I also changed things to only show the date once (as suggested on discord), I think thats a good idea.

The hardest thing was getting long titles to behave. Truncating them to the arbitrary 42 characters just doesnt work if e.g. the calendar is very wide or if 5 columns is enabled (breaks the column layout), so I ended up with something a bit more convoluted (absolutely positioned div), certainly welcome another solution there.

Anyway, let us know your thoughts or any concerns with this.

**Comment by denispapec** [comment]
Thanks, yeah, long titles annoyed me too :see_no_evil: , thanks for having a look at that and other bits. 
I've noticed one issue where it duplicates the showDate still and that is because event date is actual airDate, and I want to preserve that till rendering and not to modify early on. 

LGTM

**Review by shamoon — APPROVED** [review]
Cool, great work

**Comment by fizzyhd** [comment]
Is there a way to make the different event dot colors customizable through the yaml files?

**Pull request merged**
