### PR TITLE
Widget/todoist integration

### PR DESCRIPTION
**Pull request by Kvrnn**
## Proposed change

Adds a new service widget for Todoist. This widget allows users to display tasks based on projects, labels or custom filters.

Closes discussion [#1630](https://github.com/gethomepage/homepage/discussions/1630) with the addition of a Tasklist

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [x] Other (please explain)

Adds documentation for a new service widget.

Modified the following base files:
- `src\widgets\widgets.js`

Imports and exposes the Todoist widget to the widgets.js file.

- `src\widgets\components.js`

Imports the Todoist component to the components.js file.

- `src\utils\proxy\handlers\credentialed.js`

Includes Todoist to the list of widgets that require authentication with a bearer token.

- `src\utils\config\service-helpers.js`

Adds a custom `categories` object for the Todoist widget.

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

## How It Looks

How It Looks

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
Thanks, we dont allow setting refreshInterval in general, so please remove that. I'll check out the rest.

**Comment by shamoon** [comment]
> [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).

Ah, it would seem this was not actually done =)

**Comment by shamoon** [comment]
Oh man, todoist is a commercial not self-hosted app? Hmm... thats not really what we try to do here... =/

**Comment by shamoon** [comment]
really appreciate your work, but closing this as above for now, would love to see this for self-hosted service (of which there are a lot of good ones).

Also, in general please attribute the use of AI tools explicitly in the future.

**Comment by shamoon** [comment]
Actually I’m reconsidering the above since there’s nothing about this that precludes another widget

**Comment by Kvrnn** [comment]
Hi @shamoon! Thanks for the feedback. First time contributing so I was a bit lost. 

I ran lint and it came clean but I'm not really sure how to check pre-commit, thought it was checked when pushing git.

The use of GitHub Copilot and ChatGPT was used throughout the widget.

Anyways, would the use of third party applications be a deal breaker? Or can I set up a discussion to poll community interest?

Thanks for reviewing the code btw! I'll make any necessary changes if we move forward. Else I will look at other features requests for the meantime.

**Comment by shamoon** [comment]
Sorry, I am going to close this for now. The code needs a lot of work and it's pretty obvious that it's because it was written by AI not a human. There are all kinds of incorrect things ( https://github.com/Kvrnn/homepage/blob/17a6e37037e47c26d3c8c4eab5f49dabc8117c4e/src/widgets/todoist/categories/project.jsx#L39 https://github.com/Kvrnn/homepage/blob/17a6e37037e47c26d3c8c4eab5f49dabc8117c4e/src/widgets/todoist/categories/project.jsx#L72 ) and just really inefficient / ugly code https://github.com/Kvrnn/homepage/blob/17a6e37037e47c26d3c8c4eab5f49dabc8117c4e/src/widgets/todoist/categories/project.jsx#L25-L41 that basically it requires me to go through it line-by-line and make lots of changes.

I totally support using AI to work on software, but it shouldn't be then directly submitted as a PR. Use it to learn how to code, etc. and at the very least you need to do a very very thorough job reviewing the code it gives you.

In essence, at least for now, large chunks of AI-generated code are equivalent to a beginner level programmer, not what we're after.

Would be open to re-addressing this in the future if things change.

Thanks again

**Pull request closed without merging**
