### PR TITLE
Add Tabler icons

### PR DESCRIPTION
**Pull request by sergi0g**
feat: Add Tabler icon support

## Proposed change

This PR aims to add support for Tabler icons that can be used for services and bookmarks. Tabler icons (https://tabler-icons.io) is an icon set of nearly 5000 beautifully crafted icons that look very nice on dashboards. They are an alternative to material design icons.

## Type of change

Add new icons for services and bookmarks

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
This is fine, as you can see it’s easy enough but I’m a little worried about ending up with too many of these. Besides I guess preferring the style of them are there any other real advantages of this icon set over what we currently support?

In general we prefer that a change like this be started as a feature request and that we gauge up-votes / comments as a way to see if there really is more generalized interest. As you can imagine, there are many “beautiful” icon packs out there…

**Comment by hex-developer** [comment]
> See https://gethomepage.dev/main/more/development/#new-feature-guidelines
> 
> Please do that and we'd be happy to re-address in the future. Again, this isnt about gate-keeping or anything, we just try to balance the overall management of the codebase

OK thanks for the info. I will keep that in mind next time!

**Comment by shamoon** [comment]
No worries, thanks for understanding. I think that exists: https://github.com/gethomepage/homepage/pull/1724

**Comment by hex-developer** [comment]
> No worries, thanks for understanding. I think that exists: https://github.com/gethomepage/homepage/pull/1724

That PR was just for mdi and si icons. I was talking about making it even more generic to support all svg icons. See my example in the previous comment.

**Pull request closed without merging**
