### PR TITLE
Re-enable image optimization

### PR DESCRIPTION
**Pull request by albertopasqualetto**
## Proposed change

Re enabled image optimization from Next js.
Don't know why it was disabled.

Please test this change if it works on your end, I had some errors on mine but they are not related to my change.

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [X] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Besides the possibility of breaking things (which I think is low but perhaps non-zero), have you looked at whether this makes any appreciable improvement? The only things that use the <Image> element (that will use this setting) are the icons, which Im sure dont need this, and the mjpeg widget.

**Comment by shamoon** [comment]
@benphelps any recollection why?
https://github.com/gethomepage/homepage/commit/7de1430af6b5dda53f2982e040c61603d8784dfa

**Comment by albertopasqualetto** [comment]
@shamoon it should be a little be faster. I made this change following lighthouse benchmark suggestions for my instance.
Maybe it could be an appreciable improvement in loading page if people are using large files as icons.

**Comment by shamoon** [comment]
So seems like changing this setting does nothing without installing sharp, which will break the armv6 builds. See https://nextjs.org/docs/messages/install-sharp

Also, as-is this is only for jsdelivr.net

This is why I asked the question above, not what the nextjs feature does but if this PR actually does anything. Unfortunately, apparently not.

Thanks anyway

**Pull request closed without merging**
