### PR TITLE
add logo assets generation

### PR DESCRIPTION
**Pull request by k-egor-smirnov**
## Proposed change

Added assets generation to show splash screen on app start in iOS instead of dark screen.
Also, there will be no need in the future to generate assets for all platforms after the logo update.

IMG_6664

Closes # (issue)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by k-egor-smirnov** [comment]
reopen after reading rules pointed in my previous PR https://github.com/gethomepage/homepage/pull/2522#issuecomment-1869923200

**Comment by shamoon** [comment]
Since when does iOS require 112 versions of a single icon? Is this still relevant without #2524?

**Comment by k-egor-smirnov** [comment]
> Since when does iOS require 112 versions of a single icon

It's described here https://itnext.io/pwa-splash-screen-and-icon-generator-a74ebb8a130. TL;DR safari ~~is crap~~ can't draw splash screens so they have to be generated for all known screen resolutions

> Is this still relevant without https://github.com/gethomepage/homepage/discussions/2524?
No. This is a separate feature to PWA look better on iOS

**Comment by shamoon** [comment]
Thats a bit crazy. Here's the thing, is that splash screen better than what we get now? Honestly, I kinda dont think so? I sorta prefer to see my dashboard than the big gray screen...

IMG_2524

**Comment by shamoon** [comment]
Thanks for the effort. Again, you can open a discussion about this, as I said it’s kinda subjective

**Pull request closed without merging**
