### PR TITLE
Add Overseerr pending request management option

### PR DESCRIPTION
**Pull request by dstotz**
## Proposed change

Add new `pendingRequest` option that allows showing and optionally managing your pending Overseerr requests. The pending requests section is limited to the max height of 3x normal widget size so it will scroll once you have too many requests.

image

Example images of widget sizes and options:

image
image

Example API response body for each new request can be found on the docs: https://api-docs.overseerr.dev/

Partially Closes #1956
This request was for two unrelated enhancements to two unrelated apps. I have made the enhancement requested for the Overseerr app only.

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Just to clarify, the reasoning here, it’s really to try to keep homepage a focused piece of software. All kinds of crazy things are possible but for every random exception we make here and there it just leads to more feature creep.

sorry for the extra work you put in, next time, feel free to reach out in advance

**Comment by shamoon** [comment]
Oh, sorry I missed that this PR is entirely that. Closing as out of scope, thanks.

**Comment by shamoon** [comment]
If you want to change the PR to be read-only and have it match other listing type widgets (eg tatulli) that would work

**Comment by dstotz** [comment]
@shamoon no worries, I understand and that totally makes sense. Did I miss this part in the docs about widgets being read-only? Or is it more of an unstated rule? If so, would you accept a PR to update the developer documentation to make this requirement clear?

I'll go ahead and close this PR and open a new one after removing the request management and bringing it more in line with Tautulli

**Comment by shamoon** [comment]
Its come up more than one. I can do that, sure.

**Pull request closed without merging**
