### PR TITLE
Enhancement: Support k8s `app` IngressRoute annotation

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

See #2182

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [x] Other (please explain): enhancement

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added corresponding documentation changes.
- [x] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by hugosxm** [comment]
I see that the docker image is built with the pull request content in it, can I access that particular docker image to test ? If yes with which url ?

**Comment by shamoon** [comment]
I dont think so since its not pushed to a registry (we should set that up tho), so I think you'd have to build locally

**Comment by shamoon** [comment]
@hugosxm you can try out in `main`, its a pretty safe change

**Comment by hugosxm** [comment]
@shamoon I can confirm to you, just tested, it works exactly as expected !

I tested both case, without the app label, it works if the name of the ingress is the same ( as before the PR ), with the app label and different ingress name, works too as i wanted :)

Thanks a lot for this little PR !

I'll keep using nightly in the meantime ^^

**Pull request merged**
