### PR TITLE
Basic authenticated user visibility customization

### PR DESCRIPTION
**Pull request by discretizer**
## Proposed change

This PR add (VERY) basic customization based on user names and groups from an external authentication provider.  It only implements a basic auth provider based on the an authenticating proxy and forwarded auth headers, although it's envisioned that other authentication providers (like Oauth2) could be added latter.

This PR really is just for comment right now, as it hasn't been fully tested. 

Closes # (issue)

## Type of change

Add new feature to customize homepage visibility based on 

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
I’m sorry, I know this PR must have been a lot of work but I have to say, I’m not particularly in favor of bringing this kind of complexity inside homepage. First this, then oauth2, then LDAP etc. It’s not that it isn’t valuable it just starts to endanger the simplicity of this project. I have other project(s) where we have full user and group support and it just gets messy… fast.

Im not the arbiter of all things with this project, but that’s my thought. Again, I do appreciate the effort you’ve put in

**Comment by discretizer** [comment]
To clarify a bit, I partly agree and think any changes to Homepage should be limited to presenting custom views to authenticated users not actually authenticating users.  There are much better ways to authenticate users and good user authentication is hard. The goal here is to simply allow people to configure group or user independent views based on authenticated user information (i.e. a header or a decoded JWT).   I agree with your sentiment, but I wanted to get feedback on what I can improve or if anyone else would find this feature useful.  I plan on at trying to maintain it as a feature branch in my forked repo either way.

**Comment by jlar0che** [comment]
I was just thinking of deploying homepage for a small group of relatively technically capable people as a way to simplify knowing all the services the group has access to. Unfortunately putting this in plain view on the open internet isn't really an option. I was just thinking it would be great if hompage could be locked behind authentication. Decided to come to the github and take a look, so here I am.

Totally understand the apprehension regarding complexity, but this is a great feature and great idea. If implemented correctly it could just be a feature that can be turned on / off and not cumbersome or weighty in relation to the main aims of homepage.

A few years ago I whipped up a manual static info page (like a proto homepage) that was behind ldap and autheticated via AD. It was dead-simple code-wise.

**Comment by shamoon** [comment]
If all you want is auth, use a reverse proxy. As noted above, that’s not really the purpose of this PR

**Comment by shamoon** [comment]
Im going to close this out as discussed above. Thank you for the effort, really. 

In the future perhaps you may want to discuss something like this in advance.

**Pull request closed without merging**
