### PR TITLE
Implemented tcp-ping as a service to check non http(s) connections

### PR DESCRIPTION
**Pull request by DonFU1**
## Proposed change

Closes # (issue)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [ ] If applicable, I have added corresponding documentation changes.
- [ ] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [ ] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
I am not clear what request or issue this is targeting 

Ping does this already and has nothing to do with https, it uses icmp because it calls ping on the underlying host

So I’ll close it. Feel free to add more context but the guidelines are pretty clear about the first point anyway.

**Comment by DonFU1** [comment]
I was trying to implement a feature to check non-http(s) connections. I choose tcp-ping as base package and build a service called "tcphandshake" around that. This way I can check if a specific port is reachable. 
Best regards

**Comment by DonFU1** [comment]
> I am not clear what request or issue this is targeting
> 
> Ping does this already and has nothing to do with https, it uses icmp because it calls ping on the underlying host
> 
> So I’ll close it. Feel free to add more context but the guidelines are pretty clear about the first point anyway.

As ICMP is only to see if a device is online, you could use this tcp-ping to check if a specific port is actually accepting connections. I actually need that for my homepage usecase.

**Comment by shamoon** [comment]
I see. Then again I’ll refer you to the guidelines linked in the template, a feature request demonstrating community interest is a requirement

Thanks

**Pull request closed without merging**
