### PR TITLE
PR - Merge documentation updates

### PR DESCRIPTION
**Pull request by Tharic99**
## Proposed change

Widget documentation updates to include the name of the widget, a url link to the widget's "home page", such as the github or main site page and a copy/paste short description of the widget item for ease of use.

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X ] If applicable, I have added corresponding documentation changes.
- [X ] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [N/A ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks but we don’t accept AI generated PRs.

**Comment by Tharic99** [comment]
I'm not sure what you mean by AI generated PRs? I spent about five hours on Friday manually going through each one of these files and updating them.

**Comment by shamoon** [comment]
Gotcha. I assumed as much only because I couldn’t imagine someone would spend the time to do this manually for something that no one has asked for. Perhaps in the future with PRs you might want to ask before investing so much of your time, I feel badly about that.

The thing is I don’t want to maintain a list of other people’s project descriptions in our docs. It’s just kind of unnecessary. I’m fine with adding the links, if you did them manually then hopefully they’re mostly accurate. 

Do you want to change this PR to be just the links? If so can re-open

**Comment by Tharic99** [comment]
Isn't that the point behind using a platform like Git? If someone (myself)
feels something is beneficial, the functionality is there for them to
simply do the work and make the updates themselves.

While you may feel it's unnecessary, I've been using Homepage for a while
now and consistently find that when I see a Widget in the documentation, I
have no idea what it is. So I felt it would be easier to simply include a
link for the widget directly in the docs, along with a brief description,
taken directly from the target site's verbiage.

**Comment by shamoon** [comment]
Yes it’s open to all but using git has nothing to do with PRs being accepted, that’s always up to project maintainers, it’s up to us to keep a project on track and verify the quality / usefulness / whatever of a PR.

I think you will find most projects have a much higher barrier to entry for PRs so they don’t end up in this situation (people have done work already and are disappointed if it doesn’t get merged).

Again, happy to re-open if it’s just links. Sorry if that doesn’t totally make sense to you

**Comment by shamoon** [comment]
Ps. You can always maintain your own fork. It’s another thing git makes possible.

**Comment by Tharic99** [comment]
I'm not sure what you mean by "if it's just links"

**Comment by Tharic99** [comment]
[PR 2737](https://github.com/gethomepage/homepage/pull/2737) submitted

**Pull request closed without merging**
