### PR TITLE
Feature: Added discover bookmarks from compose file (#1930)

### PR DESCRIPTION
**Pull request by rod7760**
## Proposed change

Added feature to discover bookmark labels from docker compose file. 

Bookmark label format is:
`homepage.bookmarks.this_is_bookmark_group.this_is_bookmark_name.this_is_bookmark_abbr="href"`

Implements Part Of #1930

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [x] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added corresponding documentation changes.
- [ ] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using pre-commit hooks and linting checks with `pnpm lint` (see development guidelines).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by rod7760** [comment]
I left some TODOs in the code about things I was not certain about.

**Review by shamoon — CHANGES_REQUESTED** [review]
Thanks for the PR. However, there are some issues with this.

The most significant issue is the syntax for the label is pretty unintuitive, imho. `homepage.bookmarks.group1.portainer.PT=http: //192.168.0.106:9000/`, i.e. it is totally arbitrary to do `bookmarks.GROUP.NAME.ABBR=URL` and way too inflexible (how about a space in the name?). It may seem more cumbersome, but this should mirror that of services where properties are defined per label, e.g. 

```
homepage.bookmarks.portainer.name=My Portainer
homepage.bookmarks.portainer.href=http: //192.168.0.106:9000/
homepage.bookmarks.portainer.abbr=PT
homepage.bookmarks.portainer.icon=
...
```

Also, this doesnt support kubernetes, which is going to be a problem (not for me, but basically a guaranteed complaint).

Before we address the code or any TODOs, let us know your thoughts on the above, we will need to address these issues for this to get merged. Either way, please let us know whether you think you will be able to do so or not.

Thanks again, do appreciate the PR.

**Comment by rod7760** [comment]
Thanks for the quick response! I'll make the changes you asked for this weekend. I may have questions about the Kubernetes support, but I am sure I can reference some of the existing code.

**Comment by rod7760** [comment]
I changed the labels to the requested format. I didn't get a chance to explore the Kubernetes integration, but I'll familiarize myself with Kubernetes sometime this week and get back to this.

**Comment by rod7760** [comment]
I made the Kubernetes changes in `src/utils/config/bookmark-helpers.js`. 

However, I am struggling to understand how to test them. This is my [kubernetes.yaml](https://github.com/rod7760/homepage-test/blob/master/app/config/kubernetes.yaml). Is this the only config file that I need for Kubernetes? Or is there an external one like docker's `compose.yaml`.

**Comment by shamoon** [comment]
I've significantly reworked this, perhaps you can test it out.

Take a look at the docs here for an example, labels should work such that you can specify multiple bookmarks on a single container (which necessitates the 'key') since they really have nothing to do with a container. I also dont think the kubernetes code worked at all. And I refactored some shared code, as discussed.

**Comment by shamoon** [comment]
Thanks for your contribution. Please reopen if / when needed.

**Pull request closed without merging**
