### PR TITLE
Enhancement: handle immich v1.118 breaking API change

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Closes #4100

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [ ] If applicable, I have added corresponding documentation changes.
- [ ] If applicable, I have reviewed the [feature](https://gethomepage.dev/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines).
- [ ] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/more/development/#code-linting).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by AndyPro720** [comment]
Hey this seems to be throwing a bug with the 1.118 immich version like so

`API Error: Cannot GET /api/server-info/stats`

**Comment by MSommer95** [comment]
Hey, I think the new Endpoint should be `server` instead of `server-info` according to immich.

**Comment by MohamedFBoussaid** [comment]
> Hey, I think the new Endpoint should be `server` instead of `server-info` according to immich.
> 
> ```
> •	/api/server-info/* has been removed. Use /api/server/* instead.
> ```

I confirm that the API calls are still breaking 
Screenshot 2024-10-16 at 10 41 03


@shamoon here is the release note from immich https://github.com/immich-app/immich/releases/tag/v1.118.0#:~:text=/api/server%2Dinfo/*%20has%20been%20removed.%20Use%20/api/server/*%20instead.

**Comment by TheSpartaGod** [comment]
@MohamedFBoussaid have you tried adding 'version: 2' for the immich widget in services.yaml? Adding that worked for me.

**Comment by nisball** [comment]
Also still broken here after pulling the latest homepage build.

image

**Comment by blue-kaleidoscope** [comment]
Are you sure this is really fixed?
image
image

It still tries to use /api/server-info/stat on my side which is deprecated according to [immich v1.118.0](https://github.com/immich-app/immich/releases/tag/v1.118.0).

**Pull request merged**
