### PR TITLE
Feature: SWAG dashboard widget

### PR DESCRIPTION
**Pull request by quietsy**
## Proposed change

Added a widget for [SWAG Dashboard](https://github.com/linuxserver/docker-mods/tree/swag-dashboard) as requested by our SWAG users.

swagdashboard

## Type of change

- [X] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thank you for the PR. Please review the feature requirements you checked off above, which do explicitly require a feature request that has been up-voted. We of course will be happy to re-address at a later time

**Comment by quietsy** [comment]
> Thank you for the PR. Please review the feature requirements you checked off above, which do explicitly require a feature request that has been up-voted. We of course will be happy to re-address at a later time

Here's the [feature request](https://github.com/gethomepage/homepage/discussions/3524).

**Comment by Graham1808** [comment]
@shamoon will this now be reopened?

**Comment by shamoon** [comment]
Sure

**Review by shamoon — APPROVED** [review]
Thanks, looks good

**Pull request merged**
