### PR TITLE
Update pihole.md with note for v6

### PR DESCRIPTION
**Pull request by MarsAgainstVenus**
## Proposed change

Closes # (issue)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation only
- [ ] Other (please explain)

## Checklist:

- [ ] If applicable, I have added corresponding documentation changes.
- [ ] If applicable, I have reviewed the [feature](https://gethomepage.dev/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines).
- [ ] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/more/development/#code-linting).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for the PR, these seem like specific things you came up against but not really been an issue for others.

**Comment by MarsAgainstVenus** [comment]
I doubt many people are running v6 yet since it's still in beta. But with the project (hopefully) exiting beta soon, I thought you may want to get ahead of all of the questions with a simple note.

**Comment by shamoon** [comment]
Sure, we just try to keep the docs as short as possible. The port note has nothing to do with this (and isn't strictly accurate) and for the key thing, I also dont think its accurate, 2FA is not required (it's "Configure application password")

**Comment by MarsAgainstVenus** [comment]
Ah, I guess I misread the "Configure app password" section. I thought it was saying that 2FA was required. And I couldn't get it to connect without the port number but I removed it and everything is working so IDK what was going on...

Anyway, thanks for taking the time to respond!

**Pull request closed without merging**
