### PR TITLE
Chore: add pre-commit and prettier to devcontainer

### PR DESCRIPTION
**Pull request by Flo2410**
## Proposed change

It's pretty annoying to have to install the pre-commit package every time the devcontainer is rebuilt.
Therefore, this PR adds the installation of the pre-commit package to the Dockerfile.

Furthermore, this PR adds the prettier VS Code extiontion to the devcontainer.  

Closes # N/A

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [ ] If applicable, I have added corresponding documentation changes.
- [ ] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Sure, I dont use the devcontainer but might as well improve it if we have it. Should we pip install the https://github.com/gethomepage/homepage/blob/main/requirements.txt instead? That also avoids maintaining this in two places

**Comment by Flo2410** [comment]
Sure, we can do that as well.

**Review by shamoon — APPROVED** [review]
Great thanks

**Comment by Flo2410** [comment]
Ahm... I'm super sorry, but just found out the requirements can't be installed in the Dockerfile. I moved the installation to the setup.sh instead. 

Again, I'm sorry, as you already merged this PR.

**Comment by shamoon** [comment]
No worries, you can open a new one. I should've really tested it out, was just going off you

**Comment by Flo2410** [comment]
Okay. I'll make a new one. Ya, I forgot to properly test as well before I pushed it and wasn't quick enough before you merged it, sorry.

**Pull request merged**
